export const experiencesObject: object = [
{
    imgSrc: '../assets/images/resume/accenture_logo.png',
    styleImg: 'height: 180px; margin-right:60px',
    styleH5: 'float: auto; margin-top: 10px;margin-left: 50px;',
    companyName: 'Accenture',
    pStyle: 'margin-left: 50px;',
    duration: '11/2021 - Currently Working',
    role: 'Senior Full Stack Engineer',
    projectTitle: '',
    task: '',
    url: [],
},
{
    imgSrc: '../assets/images/resume/accenture_logo.png',
    styleImg: 'height: 180px; margin-right:60px',
    styleH5: 'float: auto; margin-top: 10px;margin-left: 50px;',
    companyName: 'Accenture',
    pStyle: 'margin-left: 50px;',
    duration: '09/2020 - 10/2021',
    role: 'Full Stack Engineer',
    projectTitle: '',
    task: 'Major responsibilities at the role included writing highly optimized business logic, requirements gathering and grooming of the user stories. Acted as the lead developer for any requirement related to Lightning Web Components. Also worked to develop internal asset for Accenture, in parallel to the client facing project work. Worked on Technical Debt user stories to reduce the overall technical debt of the system by 10%. Responsible for mentoring a new joiners in the project, so that they are able to get familiar with the ecosystem as well as guide them through Salesforce.com development challenges and issues. Resolved critical and high risk defects with the least turn around time across the team. Acted as a sole developer for developing 2 Sprints of critical business requirements',
    url: [],
},
{
    imgSrc: '../assets/images/resume/ribbon_communication_logo.png',
    styleImg: 'height: 200px; float: left; margin-right: 10px;',
    styleH5: 'float: auto; margin-top: 10px;margin-left: 50px;',
    companyName: 'Ribbon Communications',
    pStyle: 'margin-left: 50px;',
    duration: '01/2020 - 04/2020',
    role: 'Software Engeering Intern',
    projectTitle: 'Easy Configuration Wizard for SBC',
    task:'During the course of the internship I assisted the SBC development team in enhancing the EMA. Also I was the lead developer in building of the Configuration Wizard, a tool which would reduce the configuration time requiered to configure a SBC. It supported IP-PBX SIP Trunk and Microsoft Teams configuration using Angular and NodeJs',
    url: [],
},
{
    imgSrc: '../assets/images/resume/spectral insights.png',
    styleImg: 'height: 180px; width: 180px;float: left; margin-right: 60px;',
    styleH5: 'float: auto; margin-top: 10px;margin-left: 50px;',
    companyName: 'Spectral Insights - An nference Inc. Company',
    pStyle: 'margin-left: 50px;',
    duration: '05/2019 - 07/2019',
    role: 'Image Processing and Algorithms Intern',
    projectTitle: 'Maximal Similarity Based Region Merging',
    task:'Developed a framework to perform region merging of image segmented into superpixels using statistical region merging and spectral clustering approaches. Focused the work in languages Python and C++ and used libraries such as OpenCV, Eigen3, Armadillo, Numpy.',
    url: [],
},
{
    imgSrc: '../assets/images/resume/soai_logo.jpg',
    styleImg: 'height: 180px; width: 180px;float: left; margin-right: 60px;',
    styleH5: 'float: auto; margin-top: 10px;margin-left: 50px;',
    companyName: 'School of AI',
    pStyle: 'margin-left: 50px;',
    duration: '06/2019 - 09/2019',
    role: 'Research Fellow',
    projectTitle:'Migrating from Classical Machine Learning to Quantum Machine Learning: An overview and case study on Drug Discovery',
    task:'Worked towards finding a Quantum Computing approach towards drug discovery and provided certain comparisions with the classical computing approach.',
    url: [
    {
        link: 'http://bit.ly/quantum-DTI-paper',
        title: 'Research Paper',
    },
    {
        link: 'http://bit.ly/quantum-DTI',
        title: 'Google Colaboratory Notebook',
    },
    ],
},
];
